[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "xslt"
    version = "@project.version@"
    path = "../xslt-native/build/libs/xslt-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-api"
    version = "@axiom.version@"
    path = "./lib/axiom-api-@axiom.version@.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-impl"
    version = "@axiom.version@"
    path = "./lib/axiom-impl-@axiom.version@.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "jakarta.activation"
    version = "@jakarta.activation.version@"
    path = "./lib/jakarta.activation-@jakarta.activation.version@.jar"
    groupId = "com.sun.activation"
    modules = ["xslt"]
