[package]
org = "ballerina"
name = "xslt"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../xslt-native/build/libs/xslt-native-@project.version@.jar"
groupId = "org.ballerinalang.xslt"
artifactId = "xslt"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/axiom-api-@axiom.version@.jar"
groupId = "org.apache.ws.commons.axiom"
artifactId = "axiom-api"
version = "@axiom.version@"

[[platform.java11.dependency]]
path = "./lib/axiom-impl-@axiom.version@.jar"
groupId = "org.apache.ws.commons.axiom"
artifactId = "axiom-impl"
version = "@axiom.version@"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-@jakarta.activation.version@.jar"
groupId = "com.sun.activation"
artifactId = "jakarta.activation"
version = "@jakarta.activation.version@"
