[package]
org = "ballerina"
name = "xslt"
version = "@toml.version@"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/xslt-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-@jakarta.activation.version@.jar"
version = "@jakarta.activation.version@"
