[package]
org = "ballerina"
name = "xslt"
version = "2.1.0"
authors = ["Ballerina"]
keywords = ["xslt", "xml", "html", "xsl", "transformation"]
repository = "https://github.com/ballerina-platform/module-ballerina-xslt"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/xslt-native-2.1.0.jar"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
version = "1.2.2"
